BEGIN;

CREATE TABLE IF NOT EXISTS tgmsg (
		id SERIAL PRIMARY KEY,
		msg JSON NOT NULL, 
		chat INT NOT NULL);

CREATE TABLE IF NOT EXISTS tghistory (
		id SERIAL PRIMARY KEY,
		msg JSON NOT NULL,
		msg_id int NOT NULL);

COMMIT;